obs:
  comment-with-api:
    reuns-on: ubuntu-latest
    steps:
      -name: Crate comment with API
      run: |
        gh api -X POST \
          http://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
          -f body='
          Comment but from the API
          '
        env:
          GITHUB_TOKEN:${{ secrets.GITHUB.TOKEN }}
          ORGANIZATION:${{ github.event.organisation.login }}
          REPOSITORY:${{ github.event.repository.name }}
          ISSUE_NUMBER? ${{ github.event.issue.number }}
